# Contract specifications for futures trading
# All values must be deterministic and match exchange standards

ES:
  root: ES
  multiplier: 50
  point_value: 50
  tick_size: 0.25
  currency: USD
  fx_base: USD

NQ:
  root: NQ
  multiplier: 20
  point_value: 20
  tick_size: 0.25
  currency: USD
  fx_base: USD

ZN:
  root: ZN
  multiplier: 1000
  point_value: 31.25
  tick_size: 0.0078125
  currency: USD
  fx_base: USD

CL:
  root: CL
  multiplier: 1000
  point_value: 1000
  tick_size: 0.01
  currency: USD
  fx_base: USD

GC:
  root: GC
  multiplier: 100
  point_value: 100
  tick_size: 0.1
  currency: USD
  fx_base: USD

6E:
  root: 6E
  multiplier: 125000
  point_value: 125000
  tick_size: 0.00005
  currency: USD
  fx_base: USD

RTY:
  root: RTY
  multiplier: 50
  point_value: 50
  tick_size: 0.1
  currency: USD
  fx_base: USD

UB:
  root: UB
  multiplier: 1000
  point_value: 1000
  tick_size: 0.03125
  currency: USD
  fx_base: USD

ZF:
  root: ZF
  multiplier: 1000
  point_value: 1000
  tick_size: 0.0078125
  currency: USD
  fx_base: USD

ZT:
  root: ZT
  multiplier: 2000
  point_value: 2000
  tick_size: 0.0078125
  currency: USD
  fx_base: USD

6B:
  root: 6B
  multiplier: 62500
  point_value: 62500
  tick_size: 0.0001
  currency: USD
  fx_base: USD

6J:
  root: 6J
  multiplier: 12500000
  point_value: 12500000
  tick_size: 0.0000005
  currency: USD
  fx_base: USD

SR3:
  root: SR3
  multiplier: 2500
  point_value: 25.00
  tick_size: 0.0025
  currency: USD
  fx_base: USD

# Aliases for database symbol mapping
aliases:
  ES_FRONT_CALENDAR_2D: ES
  NQ_FRONT_CALENDAR_2D: NQ
  ZN_FRONT_VOLUME: ZN
  CL_FRONT_VOLUME: CL
  GC_FRONT_VOLUME: GC
  6E_FRONT_CALENDAR_2D: 6E
  RTY_FRONT_CALENDAR_2D: RTY
  UB_FRONT_VOLUME: UB
  ZF_FRONT_VOLUME: ZF
  ZT_FRONT_VOLUME: ZT
  6B_FRONT_CALENDAR_2D: 6B
  6J_FRONT_CALENDAR_2D: 6J
  SR3_FRONT_CALENDAR_2D: SR3

